#/=========\#
#| By Lewy |#
#\=========/#

################
### MONITORS ###
################

    # to enable a conf on all monitors let the key empty
    # to not use a conf just use anything eg. a x -> $monitor1 = x
    # ONLY ONE MONITOR PER VARIABLE (or all when empty)

        $monitor1 = eDP-1
        $monitor2 = HDMI-A-1
        $monitor3 = x

    # to add more monitors: (replace the <x>/<y> suffix with wather you want, use everywhere the same suffix for one manitor)
    #
    #   add another variable here ->    $monitor4 = x
    #   in updateVar.sh:
    #       add in 1.1 ->   monitor<x>=$(grep -E "^\s*\\\$monitor<x>\s*=" "$SETTINGS" | cut -d'=' -f2 | xargs)
    #       add in 1.2 ->   "monitor<x>"
    #       add in 2.2 ->   scale_values "<monitor<x>>" "<<y>>" <default_height>
    #
    #   in $HOME/.config/hypr/hyprlock.conf
    #       add a $monitor<x> variable in the MONITORS section below the other monitor variables
    #       copy a whole MONITOR1/MONITOR2/MONITOR3 section and paste it below your last monitor section
    #       add the source of the file, that you will create below, in the SOURCES section at the bottom of the hyprlock.conf file
    #
    #   copy one of the $HOME/.config/hypr/HyprLockConfig/Monitors/monitor<x>.conf files
    #       replace all of the m1/m2/m3 suffix with <y>
    #       replace all the monitor1/monitor2/monitor3 by monitor<x>
    #
    #   Now you have a new monitor :)

################
### BOOKMARK ###
################

    # X-Coords of the Bookmark (in %)
        # -50
        $bookmarkX = -1.953125

    # Y-Coords of the Bookmark (in %)
        # -100
        $bookmarkY = -6.25
